/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthenticatedTeacherRouteRouteImport } from './routes/_authenticated/teacher/route'
import { Route as AuthenticatedAdminAcademicRouteImport } from './routes/_authenticated/admin/academic'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedStudentAnalyticsRouteImport } from './routes/_authenticated/student/analytics'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentHistoryRouteImport } from './routes/_authenticated/student/history'
import { Route as AuthenticatedStudentPerformanceRouteImport } from './routes/_authenticated/student/performance'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedStudentTestsRouteImport } from './routes/_authenticated/student/tests'
import { Route as AuthenticatedTeacherClassesRouteImport } from './routes/_authenticated/teacher/classes'
import { Route as AuthenticatedTeacherCreateTestRouteImport } from './routes/_authenticated/teacher/create-test'
import { Route as AuthenticatedTeacherDashboardRouteImport } from './routes/_authenticated/teacher/dashboard'
import { Route as AuthenticatedTeacherProfileRouteImport } from './routes/_authenticated/teacher/profile'
import { Route as AuthenticatedTeacherQuestionBankRouteImport } from './routes/_authenticated/teacher/question-bank'
import { Route as AuthenticatedTeacherTestsRouteImport } from './routes/_authenticated/teacher/tests'
import { Route as AuthenticatedStudentTakeTestAttemptIdRouteImport } from './routes/_authenticated/student/take-test.$attemptId'
import { Route as AuthenticatedStudentTestResultAttemptIdRouteImport } from './routes/_authenticated/student/test-result.$attemptId'
import { Route as AuthenticatedTeacherClassClassIdRouteImport } from './routes/_authenticated/teacher/class.$classId'
import { Route as AuthenticatedTeacherStudentStudentIdRouteImport } from './routes/_authenticated/teacher/student.$studentId'
import { Route as AuthenticatedTeacherClassClassIdAnalyticsRouteImport } from './routes/_authenticated/teacher/class.$classId.analytics'
import { Route as AuthenticatedTeacherClassClassIdStudentsRouteImport } from './routes/_authenticated/teacher/class.$classId.students'
import { Route as AuthenticatedTeacherTestTestIdResultsRouteImport } from './routes/_authenticated/teacher/test.$testId.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherRouteRoute =
  AuthenticatedTeacherRouteRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAcademicRoute =
  AuthenticatedAdminAcademicRouteImport.update({
    id: '/academic',
    path: '/academic',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedStudentAnalyticsRoute =
  AuthenticatedStudentAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentHistoryRoute =
  AuthenticatedStudentHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentPerformanceRoute =
  AuthenticatedStudentPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentTestsRoute =
  AuthenticatedStudentTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedTeacherClassesRoute =
  AuthenticatedTeacherClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherCreateTestRoute =
  AuthenticatedTeacherCreateTestRouteImport.update({
    id: '/create-test',
    path: '/create-test',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherDashboardRoute =
  AuthenticatedTeacherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherProfileRoute =
  AuthenticatedTeacherProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherQuestionBankRoute =
  AuthenticatedTeacherQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherTestsRoute =
  AuthenticatedTeacherTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentTakeTestAttemptIdRoute =
  AuthenticatedStudentTakeTestAttemptIdRouteImport.update({
    id: '/take-test/$attemptId',
    path: '/take-test/$attemptId',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentTestResultAttemptIdRoute =
  AuthenticatedStudentTestResultAttemptIdRouteImport.update({
    id: '/test-result/$attemptId',
    path: '/test-result/$attemptId',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedTeacherClassClassIdRoute =
  AuthenticatedTeacherClassClassIdRouteImport.update({
    id: '/class/$classId',
    path: '/class/$classId',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherStudentStudentIdRoute =
  AuthenticatedTeacherStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherClassClassIdAnalyticsRoute =
  AuthenticatedTeacherClassClassIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedTeacherClassClassIdRoute,
  } as any)
const AuthenticatedTeacherClassClassIdStudentsRoute =
  AuthenticatedTeacherClassClassIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedTeacherClassClassIdRoute,
  } as any)
const AuthenticatedTeacherTestTestIdResultsRoute =
  AuthenticatedTeacherTestTestIdResultsRouteImport.update({
    id: '/test/$testId/results',
    path: '/test/$testId/results',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/admin/academic': typeof AuthenticatedAdminAcademicRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/student/analytics': typeof AuthenticatedStudentAnalyticsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/performance': typeof AuthenticatedStudentPerformanceRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/tests': typeof AuthenticatedStudentTestsRoute
  '/teacher/classes': typeof AuthenticatedTeacherClassesRoute
  '/teacher/create-test': typeof AuthenticatedTeacherCreateTestRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/question-bank': typeof AuthenticatedTeacherQuestionBankRoute
  '/teacher/tests': typeof AuthenticatedTeacherTestsRoute
  '/student/take-test/$attemptId': typeof AuthenticatedStudentTakeTestAttemptIdRoute
  '/student/test-result/$attemptId': typeof AuthenticatedStudentTestResultAttemptIdRoute
  '/teacher/class/$classId': typeof AuthenticatedTeacherClassClassIdRouteWithChildren
  '/teacher/student/$studentId': typeof AuthenticatedTeacherStudentStudentIdRoute
  '/teacher/class/$classId/analytics': typeof AuthenticatedTeacherClassClassIdAnalyticsRoute
  '/teacher/class/$classId/students': typeof AuthenticatedTeacherClassClassIdStudentsRoute
  '/teacher/test/$testId/results': typeof AuthenticatedTeacherTestTestIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/admin/academic': typeof AuthenticatedAdminAcademicRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/student/analytics': typeof AuthenticatedStudentAnalyticsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/performance': typeof AuthenticatedStudentPerformanceRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/tests': typeof AuthenticatedStudentTestsRoute
  '/teacher/classes': typeof AuthenticatedTeacherClassesRoute
  '/teacher/create-test': typeof AuthenticatedTeacherCreateTestRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/question-bank': typeof AuthenticatedTeacherQuestionBankRoute
  '/teacher/tests': typeof AuthenticatedTeacherTestsRoute
  '/student/take-test/$attemptId': typeof AuthenticatedStudentTakeTestAttemptIdRoute
  '/student/test-result/$attemptId': typeof AuthenticatedStudentTestResultAttemptIdRoute
  '/teacher/class/$classId': typeof AuthenticatedTeacherClassClassIdRouteWithChildren
  '/teacher/student/$studentId': typeof AuthenticatedTeacherStudentStudentIdRoute
  '/teacher/class/$classId/analytics': typeof AuthenticatedTeacherClassClassIdAnalyticsRoute
  '/teacher/class/$classId/students': typeof AuthenticatedTeacherClassClassIdStudentsRoute
  '/teacher/test/$testId/results': typeof AuthenticatedTeacherTestTestIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/_authenticated/admin/academic': typeof AuthenticatedAdminAcademicRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/student/analytics': typeof AuthenticatedStudentAnalyticsRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/history': typeof AuthenticatedStudentHistoryRoute
  '/_authenticated/student/performance': typeof AuthenticatedStudentPerformanceRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/tests': typeof AuthenticatedStudentTestsRoute
  '/_authenticated/teacher/classes': typeof AuthenticatedTeacherClassesRoute
  '/_authenticated/teacher/create-test': typeof AuthenticatedTeacherCreateTestRoute
  '/_authenticated/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/_authenticated/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/_authenticated/teacher/question-bank': typeof AuthenticatedTeacherQuestionBankRoute
  '/_authenticated/teacher/tests': typeof AuthenticatedTeacherTestsRoute
  '/_authenticated/student/take-test/$attemptId': typeof AuthenticatedStudentTakeTestAttemptIdRoute
  '/_authenticated/student/test-result/$attemptId': typeof AuthenticatedStudentTestResultAttemptIdRoute
  '/_authenticated/teacher/class/$classId': typeof AuthenticatedTeacherClassClassIdRouteWithChildren
  '/_authenticated/teacher/student/$studentId': typeof AuthenticatedTeacherStudentStudentIdRoute
  '/_authenticated/teacher/class/$classId/analytics': typeof AuthenticatedTeacherClassClassIdAnalyticsRoute
  '/_authenticated/teacher/class/$classId/students': typeof AuthenticatedTeacherClassClassIdStudentsRoute
  '/_authenticated/teacher/test/$testId/results': typeof AuthenticatedTeacherTestTestIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/academic'
    | '/admin/dashboard'
    | '/student/analytics'
    | '/student/dashboard'
    | '/student/history'
    | '/student/performance'
    | '/student/profile'
    | '/student/tests'
    | '/teacher/classes'
    | '/teacher/create-test'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/tests'
    | '/student/take-test/$attemptId'
    | '/student/test-result/$attemptId'
    | '/teacher/class/$classId'
    | '/teacher/student/$studentId'
    | '/teacher/class/$classId/analytics'
    | '/teacher/class/$classId/students'
    | '/teacher/test/$testId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/academic'
    | '/admin/dashboard'
    | '/student/analytics'
    | '/student/dashboard'
    | '/student/history'
    | '/student/performance'
    | '/student/profile'
    | '/student/tests'
    | '/teacher/classes'
    | '/teacher/create-test'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/tests'
    | '/student/take-test/$attemptId'
    | '/student/test-result/$attemptId'
    | '/teacher/class/$classId'
    | '/teacher/student/$studentId'
    | '/teacher/class/$classId/analytics'
    | '/teacher/class/$classId/students'
    | '/teacher/test/$testId/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/academic'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/student/analytics'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/history'
    | '/_authenticated/student/performance'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/tests'
    | '/_authenticated/teacher/classes'
    | '/_authenticated/teacher/create-test'
    | '/_authenticated/teacher/dashboard'
    | '/_authenticated/teacher/profile'
    | '/_authenticated/teacher/question-bank'
    | '/_authenticated/teacher/tests'
    | '/_authenticated/student/take-test/$attemptId'
    | '/_authenticated/student/test-result/$attemptId'
    | '/_authenticated/teacher/class/$classId'
    | '/_authenticated/teacher/student/$studentId'
    | '/_authenticated/teacher/class/$classId/analytics'
    | '/_authenticated/teacher/class/$classId/students'
    | '/_authenticated/teacher/test/$testId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/academic': {
      id: '/_authenticated/admin/academic'
      path: '/academic'
      fullPath: '/admin/academic'
      preLoaderRoute: typeof AuthenticatedAdminAcademicRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/student/analytics': {
      id: '/_authenticated/student/analytics'
      path: '/analytics'
      fullPath: '/student/analytics'
      preLoaderRoute: typeof AuthenticatedStudentAnalyticsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/history': {
      id: '/_authenticated/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof AuthenticatedStudentHistoryRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/performance': {
      id: '/_authenticated/student/performance'
      path: '/performance'
      fullPath: '/student/performance'
      preLoaderRoute: typeof AuthenticatedStudentPerformanceRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/tests': {
      id: '/_authenticated/student/tests'
      path: '/tests'
      fullPath: '/student/tests'
      preLoaderRoute: typeof AuthenticatedStudentTestsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/teacher/classes': {
      id: '/_authenticated/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof AuthenticatedTeacherClassesRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/create-test': {
      id: '/_authenticated/teacher/create-test'
      path: '/create-test'
      fullPath: '/teacher/create-test'
      preLoaderRoute: typeof AuthenticatedTeacherCreateTestRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/dashboard': {
      id: '/_authenticated/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof AuthenticatedTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/profile': {
      id: '/_authenticated/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthenticatedTeacherProfileRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/question-bank': {
      id: '/_authenticated/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/teacher/question-bank'
      preLoaderRoute: typeof AuthenticatedTeacherQuestionBankRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/tests': {
      id: '/_authenticated/teacher/tests'
      path: '/tests'
      fullPath: '/teacher/tests'
      preLoaderRoute: typeof AuthenticatedTeacherTestsRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/student/take-test/$attemptId': {
      id: '/_authenticated/student/take-test/$attemptId'
      path: '/take-test/$attemptId'
      fullPath: '/student/take-test/$attemptId'
      preLoaderRoute: typeof AuthenticatedStudentTakeTestAttemptIdRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/test-result/$attemptId': {
      id: '/_authenticated/student/test-result/$attemptId'
      path: '/test-result/$attemptId'
      fullPath: '/student/test-result/$attemptId'
      preLoaderRoute: typeof AuthenticatedStudentTestResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/teacher/class/$classId': {
      id: '/_authenticated/teacher/class/$classId'
      path: '/class/$classId'
      fullPath: '/teacher/class/$classId'
      preLoaderRoute: typeof AuthenticatedTeacherClassClassIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/student/$studentId': {
      id: '/_authenticated/teacher/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/teacher/student/$studentId'
      preLoaderRoute: typeof AuthenticatedTeacherStudentStudentIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/class/$classId/analytics': {
      id: '/_authenticated/teacher/class/$classId/analytics'
      path: '/analytics'
      fullPath: '/teacher/class/$classId/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherClassClassIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedTeacherClassClassIdRoute
    }
    '/_authenticated/teacher/class/$classId/students': {
      id: '/_authenticated/teacher/class/$classId/students'
      path: '/students'
      fullPath: '/teacher/class/$classId/students'
      preLoaderRoute: typeof AuthenticatedTeacherClassClassIdStudentsRouteImport
      parentRoute: typeof AuthenticatedTeacherClassClassIdRoute
    }
    '/_authenticated/teacher/test/$testId/results': {
      id: '/_authenticated/teacher/test/$testId/results'
      path: '/test/$testId/results'
      fullPath: '/teacher/test/$testId/results'
      preLoaderRoute: typeof AuthenticatedTeacherTestTestIdResultsRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAcademicRoute: typeof AuthenticatedAdminAcademicRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAcademicRoute: AuthenticatedAdminAcademicRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentAnalyticsRoute: typeof AuthenticatedStudentAnalyticsRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentHistoryRoute: typeof AuthenticatedStudentHistoryRoute
  AuthenticatedStudentPerformanceRoute: typeof AuthenticatedStudentPerformanceRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentTestsRoute: typeof AuthenticatedStudentTestsRoute
  AuthenticatedStudentTakeTestAttemptIdRoute: typeof AuthenticatedStudentTakeTestAttemptIdRoute
  AuthenticatedStudentTestResultAttemptIdRoute: typeof AuthenticatedStudentTestResultAttemptIdRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentAnalyticsRoute: AuthenticatedStudentAnalyticsRoute,
    AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
    AuthenticatedStudentHistoryRoute: AuthenticatedStudentHistoryRoute,
    AuthenticatedStudentPerformanceRoute: AuthenticatedStudentPerformanceRoute,
    AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
    AuthenticatedStudentTestsRoute: AuthenticatedStudentTestsRoute,
    AuthenticatedStudentTakeTestAttemptIdRoute:
      AuthenticatedStudentTakeTestAttemptIdRoute,
    AuthenticatedStudentTestResultAttemptIdRoute:
      AuthenticatedStudentTestResultAttemptIdRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedTeacherClassClassIdRouteChildren {
  AuthenticatedTeacherClassClassIdAnalyticsRoute: typeof AuthenticatedTeacherClassClassIdAnalyticsRoute
  AuthenticatedTeacherClassClassIdStudentsRoute: typeof AuthenticatedTeacherClassClassIdStudentsRoute
}

const AuthenticatedTeacherClassClassIdRouteChildren: AuthenticatedTeacherClassClassIdRouteChildren =
  {
    AuthenticatedTeacherClassClassIdAnalyticsRoute:
      AuthenticatedTeacherClassClassIdAnalyticsRoute,
    AuthenticatedTeacherClassClassIdStudentsRoute:
      AuthenticatedTeacherClassClassIdStudentsRoute,
  }

const AuthenticatedTeacherClassClassIdRouteWithChildren =
  AuthenticatedTeacherClassClassIdRoute._addFileChildren(
    AuthenticatedTeacherClassClassIdRouteChildren,
  )

interface AuthenticatedTeacherRouteRouteChildren {
  AuthenticatedTeacherClassesRoute: typeof AuthenticatedTeacherClassesRoute
  AuthenticatedTeacherCreateTestRoute: typeof AuthenticatedTeacherCreateTestRoute
  AuthenticatedTeacherDashboardRoute: typeof AuthenticatedTeacherDashboardRoute
  AuthenticatedTeacherProfileRoute: typeof AuthenticatedTeacherProfileRoute
  AuthenticatedTeacherQuestionBankRoute: typeof AuthenticatedTeacherQuestionBankRoute
  AuthenticatedTeacherTestsRoute: typeof AuthenticatedTeacherTestsRoute
  AuthenticatedTeacherClassClassIdRoute: typeof AuthenticatedTeacherClassClassIdRouteWithChildren
  AuthenticatedTeacherStudentStudentIdRoute: typeof AuthenticatedTeacherStudentStudentIdRoute
  AuthenticatedTeacherTestTestIdResultsRoute: typeof AuthenticatedTeacherTestTestIdResultsRoute
}

const AuthenticatedTeacherRouteRouteChildren: AuthenticatedTeacherRouteRouteChildren =
  {
    AuthenticatedTeacherClassesRoute: AuthenticatedTeacherClassesRoute,
    AuthenticatedTeacherCreateTestRoute: AuthenticatedTeacherCreateTestRoute,
    AuthenticatedTeacherDashboardRoute: AuthenticatedTeacherDashboardRoute,
    AuthenticatedTeacherProfileRoute: AuthenticatedTeacherProfileRoute,
    AuthenticatedTeacherQuestionBankRoute:
      AuthenticatedTeacherQuestionBankRoute,
    AuthenticatedTeacherTestsRoute: AuthenticatedTeacherTestsRoute,
    AuthenticatedTeacherClassClassIdRoute:
      AuthenticatedTeacherClassClassIdRouteWithChildren,
    AuthenticatedTeacherStudentStudentIdRoute:
      AuthenticatedTeacherStudentStudentIdRoute,
    AuthenticatedTeacherTestTestIdResultsRoute:
      AuthenticatedTeacherTestTestIdResultsRoute,
  }

const AuthenticatedTeacherRouteRouteWithChildren =
  AuthenticatedTeacherRouteRoute._addFileChildren(
    AuthenticatedTeacherRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedTeacherRouteRoute: typeof AuthenticatedTeacherRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedTeacherRouteRoute: AuthenticatedTeacherRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
